openapi: 3.1.0
info:
  title: Chungman Time Server API
  version: 1.0.0
  description: 충만이가 현재 시간을 인식하기 위한 API

servers:
  - url: https://gpt-time-server.onrender.com

paths:
  /get-time:
    get:
      summary: 현재 시간 가져오기 (서울 기준)
      responses:
        '200':
          description: 현재 시간 반환
          content:
            application/json:
              schema:
                type: object
                properties:
                  time:
                    type: string
