openapi: 3.1.0
info:
  title: Time API Proxy
  version: 1.0.0
servers:
  - url: https://your-render-url.onrender.com
paths:
  /get-time:
    get:
      operationId: get_current_time
      summary: Get the current time for a specific timezone
      parameters:
        - name: timezone
          in: query
          required: true
          description: Timezone in IANA format (e.g., 'Asia/Seoul')
          schema:
            type: string
      responses:
        '200':
          description: A JSON response with the current time
          content:
            application/json:
              schema:
                type: object
                properties:
                  dateTime:
                    type: string
                    example: "2025-05-09T11:13:41.1248563"
