openapi: 3.1.0
info:
  title: Simple Time Server
  version: 1.0.0
servers:
  - url: https://gpt-time-server.onrender.com
paths:
  /now:
    get:
      operationId: get_current_time
      summary: Get current time in Asia/Seoul
      responses:
        '200':
          description: Returns the current time in Seoul
          content:
            application/json:
              schema:
                type: object
                properties:
                  time:
                    type: string
                    example: "5/9/2025, 9:22:11 PM"
